# Generated by Django 5.2.4 on 2025-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='close',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pending',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
