# Generated by Django 5.2.4 on 2025-10-30 12:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE orders_order SET total = 0 WHERE total IS NULL OR total = ''",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
