# Generated by Django 5.2.4 on 2025-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20251030_0953'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DELETE FROM orders_order;",
                "DELETE FROM sqlite_sequence WHERE name='orders_order';",
            ],
            reverse_sql=migrations.RunSQL.noop
        ),
    ]