# Generated by Django 5.2.4 on 2025-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_truncate_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7, null=True),
        ),
    ]
